# Servidores
servidor_logs ansible_host=172.31.23.48
servidor_web_sftp ansible_host=127.0.0.1 ansible_connection=local
servidor_ldap ansible_host=172.31.21.7

# Aqui indicaremos los nuevos servidores
[nuevos_servidores]
servidor_audio_video ansible_host=172.31.5.110
servidor_videollamada ansible_host=172.31.10.223
servidor_base_datos ansible_host=172.31.10.25

# Variables para el playbook
[all:vars]
# Credenciales iniciales por defecto de AWS para configurar los servidores
ansible_user_inicial=ubuntu
ansible_ssh_private_key_file_inicial=ServidorWeb.pem

# Credenciales de los usuarios admin_log que lo hacemos con variable, el usuario de 
#admin_LDAP lo ponemos manualmente
nuevo_usuario_admin=admin_Logs
clave_privada_nueva=~/.ssh/id_rsa_logs
clave_publica_nueva=~/.ssh/id_rsa_logs.pub
